class NetworkError extends Error {
    constructor(message) {
      super(message);
      this.name = 'NetworkError';
    }
}
  
// TODO: 1
function fetchingUserFromInternet(isOffline){
    return new Promise((resolve,reject) => {
          if (!isOffline){
              resolve({ name: 'John', age: 18 })
          }else{
              reject(new NetworkError('Gagal mendapatkan data dari internet'))
          }
      })
  }
  
  //TODO: 2
  async function gettingUserName(){
      try{
          const user = await fetchingUserFromInternet(false);
          return user.name
      }catch(e){
          return e.message
      }
  }
  gettingUserName()
